In [1]:
import tensorflow as tf
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers

In [4]:
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]

# One cell RNN input_dim (4) -> output_dim (2)
# input 데이터 값
x_data = np.array([[h]], dtype=np.float32)

# 출력 크기 설정(내가 설정하고 싶은대로 하면 됨)
hidden_size = 2

cell = layers.SimpleRNNCell(units=hidden_size)
rnn = layers.RNN(cell, return_sequences=True, return_state=True)
outputs, states = rnn(x_data)

print('- - - - - sequence=1 - - - - -')
print('x_data: {}, shape: {}'.format(x_data, x_data.shape))
print('outputs: {}, shape: {}'.format(outputs, outputs.shape))
print('states: {}, shape: {}'.format(states, states.shape))

- - - - - sequence=1 - - - - -
x_data: [[[1. 0. 0. 0.]]], shape: (1, 1, 4)
outputs: [[[0.05271597 0.56726605]]], shape: (1, 1, 2)
states: [[0.05271597 0.56726605]], shape: (1, 2)


In [6]:
# One cell RNN input_dim (4) -> output_dim (2)
x_data = np.array([[h, e, l, l, o]], dtype=np.float32)

hidden_size = 2
cell = layers.SimpleRNNCell(units=hidden_size)
rnn = layers.RNN(cell, return_sequences=True, return_state=True)
outputs, states = rnn(x_data)

print('- - - - - sequence=5 - - - - -')
print('x_data: {}, shape: {}'.format(x_data, x_data.shape))
print('outputs: {}, shape: {}'.format(outputs, outputs.shape))
print('states: {}, shape: {}'.format(states, states.shape))

- - - - - sequence=5 - - - - -
x_data: [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]], shape: (1, 5, 4)
outputs: [[[-0.33573863  0.38469097]
  [-0.2490594   0.73866326]
  [ 0.7034957  -0.2676378 ]
  [ 0.18249114 -0.9007452 ]
  [-0.9418899  -0.6520302 ]]], shape: (1, 5, 2)
states: [[-0.9418899 -0.6520302]], shape: (1, 2)


In [ ]:
# 4분 -> Batching Input부터