In [1]:
import tensorflow as tf
import numpy as np

## 데이터 생성

In [3]:
# unique chars: h, i, e, l, o
idx2char = ['h', 'i', 'e', 'l', 'o']

# hihell
x_data = [[0, 1, 0, 2, 3, 3]]

# ihello
y_data = [[1, 0, 2, 3, 3, 4]]

num_classes = 5

# one-hot size
input_dim = 5
seq_length = 6
learning_rate = 0.1

x_one_hot = np.array([[[1, 0, 0, 0, 0], # h: 0
                       [0, 1, 0, 0, 0], # i: 1
                       [1, 0, 0, 0, 0], # h: 0
                       [0, 0, 1, 0, 0], # e: 2
                       [0, 0, 0, 1, 0], # l: 3
                       [0, 0, 0, 1, 0]  # l: 3
            ]], dtype=np.float32)

y_one_hot = tf.keras.utils.to_categorical(y_data, num_classes=num_classes)

print(x_one_hot)
print(y_one_hot)

[[[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [1. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 1. 0.]]]
[[[0. 1. 0. 0. 0.]
  [1. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]]


## 모델 생성

In [4]:
model = tf.keras.Sequential()

## 셀 생성 및 RNN 레이어에 추가

In [10]:
cell = tf.keras.layers.LSTMCell(units=num_classes, input_shape=(seq_length, input_dim))

model.add(tf.keras.layers.RNN(cell=cell, return_sequences=True))

## 완전연결층

In [11]:
model.add(tf.keras.layers.TimeDistributed(tf.keras.layers.Dense(units=num_classes, activation='softmax')))
model.compile(loss='categorical_crossentropy',
              optimizer=tf.keras.optimizers.Adam(lr=learning_rate),
              metrics=['accuracy'])

## 모델 학습

In [13]:
model.fit(x_one_hot, y_one_hot, epochs=50, verbose=1)
model.summary()

Epoch 1/50
1/1 [==============================] - 0s 16ms/step - loss: 0.0013 - accuracy: 1.0000
Epoch 2/50
1/1 [==============================] - 0s 9ms/step - loss: 0.0013 - accuracy: 1.0000
Epoch 3/50
1/1 [==============================] - 0s 8ms/step - loss: 0.0013 - accuracy: 1.0000
Epoch 4/50
1/1 [==============================] - 0s 10ms/step - loss: 0.0012 - accuracy: 1.0000
Epoch 5/50
1/1 [==============================] - 0s 7ms/step - loss: 0.0012 - accuracy: 1.0000
Epoch 6/50
1/1 [==============================] - 0s 7ms/step - loss: 0.0012 - accuracy: 1.0000
Epoch 7/50
1/1 [==============================] - 0s 7ms/step - loss: 0.0011 - accuracy: 1.0000
Epoch 8/50
1/1 [==============================] - 0s 9ms/step - loss: 0.0011 - accuracy: 1.0000
Epoch 9/50
1/1 [==============================] - 0s 9ms/step - loss: 0.0011 - accuracy: 1.0000
Epoch 10/50
1/1 [==============================] - 0s 10ms/step - loss: 0.0011 - accuracy: 1.0000
Epoch 11/50
1/1 [===================

## 예측

In [14]:
predictions = model.predict(x_one_hot)

for i, prediction in enumerate(predictions):
    print(prediction)
    
    result_str = [idx2char[c] for c in np.argmax(prediction, axis=1)]
    print("\tPrediction str: ", ''.join(result_str))

[[8.1309190e-06 9.9929607e-01 5.7420897e-04 8.8054520e-07 1.2076442e-04]
 [9.9949324e-01 2.2498580e-05 2.4760916e-04 2.3457187e-04 2.0068280e-06]
 [1.4936546e-04 2.4913755e-04 9.9918872e-01 4.1261723e-04 1.7819214e-07]
 [8.7579974e-05 7.3097888e-09 6.7213907e-05 9.9980861e-01 3.6556321e-05]
 [5.2097101e-05 4.3731575e-08 5.8486012e-06 9.9907994e-01 8.6199731e-04]
 [9.7487634e-07 2.0945592e-04 1.2094559e-08 9.3279831e-04 9.9885678e-01]]
	Prediction str:  ihello
