In [1]:
import torch
import numpy as np

### 텐서 초기화

#### 1) 데이터로부터 직접 생성

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [3]:
print(x_data)

tensor([[1, 2],
        [3, 4]])


#### 2) numpy 배열로부터 생성

In [4]:
np_array = np.array(data)

# numpy array 형태인 np_array를 tensor 형태로
x_np = torch.from_numpy(np_array)

In [5]:
print(x_np)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


1), 2)의 차이점 : 2)는 dtype이 같이 출력됨

#### 3) 다른 텐서로부터 생성

In [6]:
# ones_like : 주어진 텐서와 동일한 크기의 텐서를 1로 초기화
x_ones = torch.ones_like(x_data)

# 인자로 텐서의 속성을 지정한다면 속성이 override됨
x_rand = torch.rand_like(x_data, dtype=torch.float)

#### 4) random 또는 상수 사용

In [7]:
shape = (2,3,)

rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

In [8]:
print(rand_tensor.dtype)
print(ones_tensor.dtype)
print(zeros_tensor.dtype)

torch.float32
torch.float32
torch.float32


### 텐서의 연산

#### 인덱싱과 슬라이싱

In [9]:
# 4*4 형태의 Tensor
tensor = torch.ones(4, 4)

# tensor 1열만 0으로 초기화
tensor[:, 1] = 0

In [10]:
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


#### 텐서 합치기

In [13]:
# dim : 어느 방향으로 합칠 것인지 정하는 인자
# dim=0 : 세로 방향 / dim=1 : 가로 방향
t1 = torch.cat([tensor, tensor, tensor], dim=1)

print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


#### 산술 연산

In [ ]:
# 두 텐서 간의 행렬 곱(matrix multiplication)을 계산합니다. y1, y2, y3은 모두 같은 값을 갖습니다.
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)


# 요소별 곱(element-wise product)을 계산합니다. z1, z2, z3는 모두 같은 값을 갖습니다.
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)